### Lista de todos los usuarios
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDEzMDQzNjU2OTIsInVzZXJuYW1lIjoiamFsdmFyZW5nYSIsInJvbGUiOiJhZG1pbiJ9.w6tFIIah6EGagvF-OtUC4UjvkAs5_hV30UxHOTRljEk
### Buscar usuario por id
GET http://localhost:3000/users/f4fd9527-4332-4c4d-99a6-12397c446987

### Crear un usuario
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Prueba desde API 2",
    "username": "jalvarenga",
    "email": "juan@unah.hn",
    "phone": 89898989,
    "role": "viewer"
}

### Actualizar un usuario
PATCH http://localhost:3000/users/a80499fd-e6bc-43c7-b2f0-264d9b7c94a
Content-Type: application/json

{ 
    "role": "viewer"
}


### Eliminar un usuario
DELETE http://localhost:3000/users/4


### API para iniciar sesión
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "jalvarenga",
    "password": "45679"
}